services:
  agent:
    env_file: [.env]
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=1223251509:AAEW-yDBWEJ1kaEdSkXOGjmNdkfFnMkfyYs  agent.pipeline_config=assistant_dists/dream_mini/pipeline_conf.json''
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  mongo:
    command: mongod
    image: mongo:4.0.0
  files:
    image: julienmeerschart/simple-file-upload-download-server
version: '3.7'
