name: fromage
endpoints:
- respond
compose:
  env_file:
  - .env
  build:
    args:
      SERVICE_PORT: 8069
      SERVICE_NAME: fromage
      FLASK_APP: server
    context: .
    dockerfile: ./services/fromage/Dockerfile
  command: flask run -h 0.0.0.0 -p 8069
  environment:
  - FLASK_APP=server
  deploy:
    resources:
      limits:
        memory: 5G
      reservations:
        memory: 5G
  volumes:
  - ./services/fromage:/src
  - ./common:/src/common
  ports:
  - 8069:8069
