fromage:
- group: skills
  connector:
    protocol: http
    timeout: 3.0
    url: http://fromage:8189/respond
  dialog_formatter: state_formatters.dp_formatters:fromage_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
