dff-fromage-image-skill:
- group: skills
  connector:
    protocol: http
    timeout: 2.0
    url: http://dff-fromage-image-skill:8070/respond
  dialog_formatter: state_formatters.dp_formatters:dff_fromage_image_skill_formatter
  response_formatter: state_formatters.dp_formatters:skill_with_attributes_formatter_service
  previous_services:
  - skill_selectors
  state_manager_method: add_hypothesis
