services:
  agent-tg:
    command: sh -c 'bin/wait && python -m deeppavlov_agent.run agent.channel=telegram agent.telegram_token=5788983152:AAGUnHi-0EW90lMhevtFCAyMjKk1Ty9Hb8c agent.pipeline_config=assistant_dists/dream_multimodal/pipeline_conf.json agent.db_config=assistant_dists/dream_multimodal/db_conf.json'
    env_file: [.env]
    build:
      context: ./
      dockerfile: dockerfile_agent
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    volumes:
      - ".:/dp-agent"

version: '3.7'
